### ISSUE TITLE
[ISSUE] - Overseer - Cannot add Icon and show it on screen

### ISSUE THREAD

**Issue by Sitjakun** [Morph21/MercuryTrade-Community-Fork#59] opened 2021-02-16 20:27 UTC
**Describe the bug**
I am using .exe launcher
I cannot create new icons/progress bar or other possibilites from Overseer.
I cannot see any icons that comes from already existing profile like "Showcase".
I have jre1.8.0_281 installed on my computer and also a later version of java. It looks like trading tool is working.
I have a log error that keeps repeating : java.lang.NoClassDefFoundError: com/sun/awt/AWTUtilities

**To Reproduce**
1. Go to Overseer
2. Click on Create new, add a profile
3. Click on New,  click on Icon
4. See error : nothing is happening

**Comment by Morph21** [comment] 2021-02-16 21:16
Duplicate of #31

**Closed** 2021-02-16 21:16 UTC
Labels: bug

**Comment by Sitjakun** [comment] 2021-02-16 21:18
Thank you, I am gonna dig into this thread

**Comment by Sitjakun** [comment] 2021-02-16 21:29
I uninstalled the JDK 13 that was on my PC. And then it worked, although that is not very satisfying solution ^^
Thank you for your help, I did not know how to check previous closed issues
