### ISSUE TITLE
[FEATURE REQUEST] Minimize windows taskbar to tray?

### ISSUE THREAD

**Issue by 0vertime** [Morph21/MercuryTrade-Community-Fork#129] opened 2022-07-03 14:31 UTC
Every time I click PoE the app pops up in taskbar like this: https://gfycat.com/dependenttepidgalapagosdove
Is there a way to keep it minimized?

**Comment by Morph21** [comment] 2022-08-02 11:55
duplicate of this #128

**Closed by Morph21** 2022-08-02 11:55 UTC
Labels: feature
