### ISSUE TITLE
[BUG] Loading Circle and nothing happens

### ISSUE THREAD

**Issue by vexor187** [Morph21/MercuryTrade-Community-Fork#19] opened 2020-10-14 21:51 UTC
**Describe the bug**
Newest version of java installed opened the exe and only get a teal loading circle nothing happens.

**To Reproduce**
1 Start the application
.

**Expected behavior**
Nothing happens and I don't see it in my task manager either so I have to restart my pc to get it off my screen

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
I tried making a mercury trade folder in the %appdata% folder but that did nothing
[mercury-app.log](https://github.com/Morph21/MercuryTrade-Community-Fork/files/5381031/mercury-app.log)

**Comment by Morph21** [comment] 2020-10-14 22:09
Duplicate of #3 

Will be fixed in the nearest release

**Closed by Morph21** 2020-10-14 22:09 UTC
Labels: bug, duplicate
