### ISSUE TITLE
[BUG] - Incompatible with java 9+ (modules)

### ISSUE THREAD

**Issue by krissrex** [Morph21/MercuryTrade-Community-Fork#65] opened 2021-04-19 16:15 UTC
**Describe the bug**
Running on java 9 or above (I'm using 16) will result in errors and an infinite loading spinner.

The reason is the new module system:
`18:08:48.133 [main] ERROR ErrorHandler - java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @5971782`

<details>
<summary>Full stack trace</summary>

```java
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
18:09:03.456 [main] ERROR ErrorHandler - java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @59717824
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.fromJson(Gson.java:931)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.mercury.platform.shared.config.json.deserializer.AdrTrackerGroupDeserializer.deserialize(AdrTrackerGroupDeserializer.java:27)
	at com.mercury.platform.shared.config.json.deserializer.AdrTrackerGroupDeserializer.deserialize(AdrTrackerGroupDeserializer.java:13)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.Gson.fromJson(Gson.java:975)
	at com.mercury.platform.shared.config.json.deserializer.AdrComponentJsonAdapter.deserialize(AdrComponentJsonAdapter.java:18)
	at com.mercury.platform.shared.config.json.deserializer.AdrComponentJsonAdapter.deserialize(AdrComponentJsonAdapter.java:9)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.mercury.platform.shared.config.json.JSONHelper.readArrayData(JSONHelper.java:61)
	at com.mercury.platform.shared.config.MercuryConfigManager.load(MercuryConfigManager.java:132)
	at com.mercury.platform.core.ProdStarter.startApplication(ProdStarter.java:40)
	at com.mercury.platform.AppMain.main(AppMain.java:44)
```

</details>

**To Reproduce**
1. Install jdk/jre 9 or above
2. Run the jar. To get stacktrace, run with `java -jar MercuryTrade.jar`

**Expected behavior**
Modules should be configured to run correctly.
The program should start normally.

**Workaround**

Run with `--illegal-access=permit`:
```
java --illegal-access=permit -jar .\MercuryTrade.jar
```
or `javaw` to hide the terminal.

**Screenshots**
-none-

**Desktop (please complete the following information):**
 - Version 1.1.7

**Additional context**

```
openjdk 16 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode, sharing)
```

**Comment by Morph21** [comment] 2021-04-19 19:31
Duplicate of issue #31

**Closed by Morph21** 2021-04-19 19:31 UTC
Labels: bug

**Comment by krissrex** [comment] 2021-04-21 12:05
> Duplicate of issue #31

No it's not.  
It's not an issue of running with JDK.  
It's an issue of the java 9 module system which introduces **limits on reflection**.  

The issues in #31 are `NoClassDefFoundError`.  
The issue here is `InaccessibleObjectException`.  
I am even able to run the application here, by explicitly disabling the java 9 illegal-acces limitations...

**Comment by krissrex** [comment] 2021-04-21 12:13
It's fine if you don't intend to support jre above 8. This issue is not something that badly needs fixing.  
It can be left here as a reference if anyone wants to run on 9+.
